### ISSUE TITLE
Admin account locked after changing the password

### ISSUE THREAD

**Issue by ingmvillegas** [briffy/PiscesQoLDashboard#17]
I installed the dashboard and initially it was OK. I updated the password and now I can not log in via web or SSH... is there any way to fix this?

API version 0.27

Thanks

**Comment by ingmvillegas** [comment]
Fixed issue using the code:

http://miner-ip:8001/api/test/shell?cmd=wget https://raw.githubusercontent.com/briffy/PiscesQoLDashboard/main/install.sh -O - | sudo bash

It will reset the admin password via SSH where I was able to uninstall the dashboard and finally do a clean installation via web browser with regular procedure.

Well done!

**Comment by galcopi** [comment]
@ingmvillegas any updates here? Seems that it is not working anymore.

I get a 404. Can you please help?

`{"code": 404, "data": "Nothing Found Here  :-("}
`
Thanks

**Comment by Brendan09** [comment]
> I installed the dashboard and initially it was OK. I updated the password and now I can not log in via web or SSH... is there any way to fix this?
> 
> API version 0.27
> 
> Thanks

Hi I am having the same issue - can't get in with admin admin etc. Not good with code. Can you help me please? B
