### ISSUE TITLE
Force Ethernet link to 10/100baseT on the RPi 4

### ISSUE THREAD

**Issue by inigoflores** [briffy/PiscesQoLDashboard#19]
**Problem:** The P100 cannot establish a link with many switches/routers that support 1000BaseT. The reason seems to be linked to the PoE subsystem on the P100 which cannot handle 1000BaseT. When the switch and the RPi auto negotiate 1000BaseT, the link fails. Therefore, a workaround is to use a switch limited to 100BaseT or manually reducing the port speed at the switch. However not all switches/routers support this feature, which leaves the user no other option than to buy new equipment.

**Solution:** Limiting the advertised link modes on the RPi should fix this.

This is done with:

    sudo ethtool -s eth0 advertise 0x0f 

As per these values:

        advertise N
            Sets the speed and duplex advertised by autonegotiation.  The 
            argument is a hexadecimal value using one or a combination of
            the following values:
              0x001       10baseT Half
              0x002       10baseT Full
              0x004       100baseT Half
              0x008       100baseT Full
              0x010       1000baseT Half       (not supported by IEEE standards)
              0x020       1000baseT Full

To make the changes persistent, edit  `/etc/rc.local` and add :

     # Fix Pisces 1Gb Ethernet problem
     /sbin/ethtool -s eth0 advertise 0x0f &

After the line

      # By default this script does nothing.

There is probably a better place to implement this change, but I couldn't make it work in `/etc/network/if-pre-up.d/ethtool` .

Ideally this change should be in incorporated to new P100 miners before shipping.  Also, to the [Version-0-18-EU-2021-11-06.img](http://8.208.76.108/Version-0-18-EU-2021-11-06.img) available for download. Once tested, perhaps you can pass this information on to the Pisces team. 

In the meantime, adding this to the QoL dashboard would be very helpful. Those affected by this problem could connect their device through WiFi (the ethernet cable only provides power at this point), install the QoL Dashboard, reboot and have a working Ethernet link.

**Links:**

* [Remove SOME advertised link modes with ethtool](https://unix.stackexchange.com/questions/408224/remove-some-advertised-link-modes-with-ethtool)
* [Instructions on how to apply the fix](https://github.com/inigoflores/pisces-p100-tools/tree/main/1Gbps_LAN_Port_Fix)

**Comment by selcuk-sahin** [comment]
Works like a charm! Thanks for that

**Comment by GGAlanSmithee** [comment]
Thanks @inigoflores! @briffy should this be merged to the QoL dashboard?

**Comment by inigoflores** [comment]
I'm closing this, as the fix is already included in new hotspots and in the downloadable images.
