### ISSUE TITLE
Need to upgrade apt cache before installing php-7.3-fpm

### ISSUE THREAD

**Issue by joanmarcriera** [briffy/PiscesQoLDashboard#3]
As seen in discord, for the install script : 

`root@raspberrypi:~# apt-get install php7.3-fpm
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php7.3-fpm
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 1,286 kB of archives.
After this operation, 4,628 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian-security buster/updates/main arm64 php7.3-fpm arm64 7.3.29-1~deb10u1
  404  Not Found [IP: 199.232.174.132 80]
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-fpm_7.3.29-1~deb10u1_arm64.deb  404  Not Found [IP: 199.232.174.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
root@raspberrypi:~# `

Solved with :

`~# apt-get update `

Then : 

`root@raspberrypi:~# apt-get -y install nginx php-fpm php7.3-fpm`

**Comment by briffy** [comment]
All sorted, cheers pal!
